CREATE TABLE IF NOT EXISTS `freight_price` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `tenant_id` bigint NOT NULL DEFAULT '1' COMMENT '租户编号',
  `transport_type` tinyint NOT NULL COMMENT '运输类型：1海派 2海卡 3整柜 4美森',
  `origin` varchar(64) NOT NULL COMMENT '起运地',
  `destination` varchar(64) NOT NULL COMMENT '目的地',
  `price_mode` tinyint NOT NULL COMMENT '计价模式：1按CBM 2按KG 3整柜一口价',
  `unit_price` decimal(18,2) NOT NULL COMMENT '单价（对应 price_mode）',
  `min_price` decimal(18,2) DEFAULT NULL COMMENT '最低收费',
  `currency` varchar(16) NOT NULL DEFAULT 'CNY' COMMENT '币种',
  `valid_from` date NOT NULL COMMENT '生效开始日期',
  `valid_to` date NOT NULL COMMENT '生效结束日期',
  `status` tinyint NOT NULL DEFAULT '0' COMMENT '状态：0启用 1停用',
  `remark` varchar(255) DEFAULT NULL COMMENT '备注',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`),
  KEY `idx_tenant_route` (`tenant_id`, `transport_type`, `origin`, `destination`),
  KEY `idx_valid_period` (`valid_from`, `valid_to`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='货运价格表';
