-- 001_create_freight_order.sql
-- 国际货代业务单模块初始化脚本
-- 包含主表、货物明细、费用明细、操作日志

CREATE TABLE IF NOT EXISTS `freight_order` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `tenant_id` BIGINT NOT NULL DEFAULT 1 COMMENT '租户编号',
  `order_no` VARCHAR(32) NOT NULL COMMENT '业务编号',
  `customer_id` BIGINT NOT NULL COMMENT '客户ID',
  `customer_name` VARCHAR(128) NOT NULL COMMENT '客户名称快照',
  `contact_name` VARCHAR(64) DEFAULT NULL COMMENT '联系人',
  `contact_phone` VARCHAR(32) DEFAULT NULL COMMENT '联系电话',
  `biz_type` VARCHAR(32) NOT NULL COMMENT '业务类型',
  `transport_mode` VARCHAR(32) NOT NULL COMMENT '运输方式',
  `incoterms` VARCHAR(16) DEFAULT NULL COMMENT '贸易条款',
  `origin_port` VARCHAR(64) NOT NULL COMMENT '起运港',
  `destination_port` VARCHAR(64) NOT NULL COMMENT '目的港',
  `pickup_address` VARCHAR(255) DEFAULT NULL COMMENT '提货地址',
  `delivery_address` VARCHAR(255) DEFAULT NULL COMMENT '送货地址',
  `carrier_name` VARCHAR(64) DEFAULT NULL COMMENT '船公司/航司',
  `cargo_name` VARCHAR(128) DEFAULT NULL COMMENT '货物品名',
  `hs_code` VARCHAR(32) DEFAULT NULL COMMENT 'HS CODE',
  `package_count` INT DEFAULT 0 COMMENT '件数',
  `package_type` VARCHAR(32) DEFAULT NULL COMMENT '包装类型',
  `gross_weight_kg` DECIMAL(18, 3) DEFAULT 0 COMMENT '毛重KG',
  `volume_cbm` DECIMAL(18, 3) DEFAULT 0 COMMENT '体积CBM',
  `container_info` VARCHAR(128) DEFAULT NULL COMMENT '箱型箱量',
  `has_battery` TINYINT NOT NULL DEFAULT 0 COMMENT '是否带电',
  `is_sensitive` TINYINT NOT NULL DEFAULT 0 COMMENT '是否敏感货',
  `customs_type` VARCHAR(32) DEFAULT NULL COMMENT '报关方式',
  `shipping_mark` VARCHAR(255) DEFAULT NULL COMMENT '唛头',
  `booking_no` VARCHAR(64) DEFAULT NULL COMMENT '订舱号',
  `so_no` VARCHAR(64) DEFAULT NULL COMMENT 'SO号',
  `bl_no` VARCHAR(64) DEFAULT NULL COMMENT '提单号',
  `container_no` VARCHAR(64) DEFAULT NULL COMMENT '柜号',
  `seal_no` VARCHAR(64) DEFAULT NULL COMMENT '封条号',
  `customs_no` VARCHAR(64) DEFAULT NULL COMMENT '报关单号',
  `pickup_time` DATETIME DEFAULT NULL COMMENT '预计提货时间',
  `etd` DATETIME DEFAULT NULL COMMENT '预计离港时间',
  `eta` DATETIME DEFAULT NULL COMMENT '预计到港时间',
  `atd` DATETIME DEFAULT NULL COMMENT '实际离港时间',
  `ata` DATETIME DEFAULT NULL COMMENT '实际到港时间',
  `sign_time` DATETIME DEFAULT NULL COMMENT '签收时间',
  `currency` VARCHAR(16) DEFAULT 'USD' COMMENT '币种',
  `receivable_amount` DECIMAL(18, 2) DEFAULT 0 COMMENT '应收金额',
  `payable_amount` DECIMAL(18, 2) DEFAULT 0 COMMENT '应付金额',
  `profit_amount` DECIMAL(18, 2) DEFAULT 0 COMMENT '利润金额',
  `status` VARCHAR(32) NOT NULL COMMENT '状态',
  `sales_user_id` BIGINT DEFAULT NULL COMMENT '销售负责人',
  `operator_user_id` BIGINT DEFAULT NULL COMMENT '操作负责人',
  `remark` VARCHAR(500) DEFAULT NULL COMMENT '备注',
  `creator` VARCHAR(64) DEFAULT '' COMMENT '创建者',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` VARCHAR(64) DEFAULT '' COMMENT '更新者',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` BIT NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_order_no` (`tenant_id`, `order_no`),
  KEY `idx_customer_id` (`tenant_id`, `customer_id`),
  KEY `idx_status` (`tenant_id`, `status`),
  KEY `idx_transport_mode` (`tenant_id`, `transport_mode`),
  KEY `idx_create_time` (`tenant_id`, `create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='国际货代业务单';


CREATE TABLE IF NOT EXISTS `freight_order_cargo` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `tenant_id` BIGINT NOT NULL DEFAULT 1 COMMENT '租户编号',
  `order_id` BIGINT NOT NULL COMMENT '业务单ID',
  `cargo_name` VARCHAR(128) NOT NULL COMMENT '货物名称',
  `package_count` INT DEFAULT 0 COMMENT '件数',
  `package_type` VARCHAR(32) DEFAULT NULL COMMENT '包装类型',
  `gross_weight_kg` DECIMAL(18, 3) DEFAULT 0 COMMENT '毛重KG',
  `volume_cbm` DECIMAL(18, 3) DEFAULT 0 COMMENT '体积CBM',
  `remark` VARCHAR(255) DEFAULT NULL COMMENT '备注',
  `creator` VARCHAR(64) DEFAULT '' COMMENT '创建者',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` VARCHAR(64) DEFAULT '' COMMENT '更新者',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` BIT NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`),
  KEY `idx_order_id` (`tenant_id`, `order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='国际货代业务单货物明细';


CREATE TABLE IF NOT EXISTS `freight_order_fee` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `tenant_id` BIGINT NOT NULL DEFAULT 1 COMMENT '租户编号',
  `order_id` BIGINT NOT NULL COMMENT '业务单ID',
  `fee_type` VARCHAR(16) NOT NULL COMMENT '费用类型 RECEIVABLE/PAYABLE',
  `fee_name` VARCHAR(64) NOT NULL COMMENT '费用名称',
  `currency` VARCHAR(16) NOT NULL DEFAULT 'USD' COMMENT '币种',
  `unit_name` VARCHAR(32) DEFAULT NULL COMMENT '计费单位',
  `quantity` DECIMAL(18, 3) DEFAULT 0 COMMENT '数量',
  `unit_price` DECIMAL(18, 2) DEFAULT 0 COMMENT '单价',
  `amount` DECIMAL(18, 2) DEFAULT 0 COMMENT '金额',
  `remark` VARCHAR(255) DEFAULT NULL COMMENT '备注',
  `creator` VARCHAR(64) DEFAULT '' COMMENT '创建者',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` VARCHAR(64) DEFAULT '' COMMENT '更新者',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` BIT NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`),
  KEY `idx_order_id` (`tenant_id`, `order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='国际货代业务单费用明细';


CREATE TABLE IF NOT EXISTS `freight_order_log` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `tenant_id` BIGINT NOT NULL DEFAULT 1 COMMENT '租户编号',
  `order_id` BIGINT NOT NULL COMMENT '业务单ID',
  `action_type` VARCHAR(32) NOT NULL COMMENT '操作类型',
  `from_status` VARCHAR(32) DEFAULT NULL COMMENT '原状态',
  `to_status` VARCHAR(32) DEFAULT NULL COMMENT '新状态',
  `operator_id` BIGINT DEFAULT NULL COMMENT '操作人ID',
  `operator_name` VARCHAR(64) DEFAULT NULL COMMENT '操作人名称',
  `content` VARCHAR(500) DEFAULT NULL COMMENT '操作说明',
  `creator` VARCHAR(64) DEFAULT '' COMMENT '创建者',
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` VARCHAR(64) DEFAULT '' COMMENT '更新者',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` BIT NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`),
  KEY `idx_order_id` (`tenant_id`, `order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='国际货代业务单操作日志';
